ORDER_ASC = "asc"
ORDER_DESC = "desc"
SORT_KEY = "_sort"
ORDER_KEY = "_order"
ID_KEY = "id"

METHOD_POST = "POST"
METHOD_GET = "GET"
METHOD_DELETE = "DELETE"
METHOD_PATCH = "PATCH"
METHOD_PUT = "PUT"

